let detailsList = {
    "name": "Name",
    "email": "Email Id",
    "mobilenumber": "Mobile Number",
    "dob": "Date Of Birth",
    "age": "Age",
    "relation": "Relation Ship",
    "relationname": "Name",
    "whatsappnumber": "Whatsapp Number",
    "bloodgroup": "Blood Group",
    "refferedby": "Reffered By",
    "reasonforconsultation": "Reson for Consultation",
    "sex": "Sex",
    "height": "Height",
    "weight": "Weight",
    "address": "Address",
    "education": "Education",
    "natureofwork": "Nature of Work",
    "chiefcomplaints": "Chief Complaints",
    "presentillness": "Present Illness",
    "headache": "HeadAche",
    "dizziness": "Dizziness",
    "appetite": "Appetite",
    "chestpain": "Chest Pain",
    "abdominalpain": "Abdominal Pain",
    "menstrualcycle": "Menstrual Cycles",
    "dm": "DM",
    "htn": "HTN",
    "heartdisease": "Heart Disease",
    "thyroid": "Thyroid",
    "asthma": "Asthma",
    "surgeries": "Surgeries",
    "allergies": "Allergies",
    "grav": "Grav",
    "para": "Para",
    "abortion": "Abortion",
    "live": "Live",
    "dmfather": "DM Father History",
    "dmmother": "DM Mother History",
    "dmsibilings": "DM Siblings History",
    "htnfather": "HTN Father History",
    "htnmother": "HTN Mother History",
    "htnsibilings": "HTN Siblings History",
    "heartdiseasefather": "Heart Disease Father History",
    "heartdiseasemother": "Heart Disease Mother History",
    "heartdiseasesibilings": "Heart Disease Siblings History",
    "kidneydiseasefather": "kidney Disease Father History",
    "kidneydiseasemother": "kidney Disease Mother History",
    "kidneydiseasesibilings": "kidney Disease Siblings History",
    "asthmafather": "Asthma Father History",
    "asthmamother": "Asthma Mother History",
    "asthmasibilings": "Asthma Mother History",
    "othersfather": "Other medical details Father",
    "othersmother": "Other medical details Mother",
    "otherssiblings": "Other medical details Siblings",
    "medications": "Medications",
    "bp": "BP",
    "pulse": "Pulse",
    "heent": "HEENT",
    "neck": "Neck",
    "respsystem": "Resp System",
    "heart": "Heart",
    "abdomen": "Abdomen",
    "extremities": "Extremities",
    "gentalia": "Gentalia",
    "breast": "Breast",
    "feet": "Feet",
    "impressions": "Impression",
    "recommendations": "Recommendations",
    "labreports": "Lab Reports"
}


export default detailsList;